### Exercicios

1. Replace all occurrences of 3 with 10, arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
2. Find common elements between the two arrays, arr1 = np.array([1, 2, 3, 4, 5]), arr2 = np.array([3, 4, 5, 6, 7])
3. Reshape the array into a 2x4 matrix, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
4. Remove duplicate elements, arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
5. Split the array into three sub-arrays, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
6. Perform element-wise multiplication, arr1 = np.array([1, 2, 3, 4]), arr2 = np.array([5, 6, 7, 8])

In [2]:
import numpy as np

In [3]:
# 1. Replace all occurrences of 3 with 10, arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
arr[arr==3]=10
#arr = np.where(arr == 3, 10, arr)
arr

array([ 1,  2, 10, 10, 10, 10, 10,  4,  5])

In [4]:
# 2. Find common elements between the two arrays, arr1 = np.array([1, 2, 3, 4, 5]), arr2 = np.array([3, 4, 5, 6, 7])
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
arr_between = np.intersect1d(arr1, arr2)
arr_between

array([3, 4, 5])

In [5]:
# 3. Reshape the array into a 2x4 matrix, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape(2,4 )

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# 4. Remove duplicate elements, arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [7]:
# 5. Split the array into three sub-arrays, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.split(arr, [3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [8]:
# 6. Perform element-wise multiplication, arr1 = np.array([1, 2, 3, 4]), arr2 = np.array([5, 6, 7, 8])
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.multiply(arr1, arr2)

array([ 5, 12, 21, 32])

**Bora praticar!**  
  
Transforme o csv **dados_artificiais**, que está na pasta **dados**, para um numpy array (matriz)

In [9]:
matriz = np.loadtxt('dados_artificiais.txt', skiprows=1, usecols=(1, 2, 3))
matriz

array([[ 1.788811, 65.648102,  0.      ],
       [ 1.566784, 76.642768,  0.      ],
       [ 2.092193, 55.468185,  1.      ],
       [ 1.782471, 67.281997,  1.      ],
       [ 1.735767, 69.289008,  0.      ],
       [ 1.686975, 56.840051,  0.      ],
       [ 1.797105, 65.208973,  1.      ],
       [ 1.187349, 48.164764,  0.      ],
       [ 1.595891, 45.410648,  1.      ],
       [ 1.396282, 67.930113,  0.      ],
       [ 1.606148, 67.719604,  0.      ],
       [ 1.70759 , 45.609333,  0.      ],
       [ 1.735513, 64.845452,  0.      ],
       [ 1.672055, 39.705952,  1.      ],
       [ 1.723377, 50.05888 ,  1.      ],
       [ 1.684574, 56.545087,  1.      ],
       [ 1.733259, 37.512188,  0.      ],
       [ 1.7579  , 57.362422,  0.      ],
       [ 1.913338, 69.307246,  1.      ],
       [ 1.456048, 69.342337,  0.      ]])

In [10]:
vetor = np.array([round(i[1] / (i[0] ** 2), 2) for i in matriz])
vetor.reshape(-1,1)

array([[20.52],
       [31.22],
       [12.67],
       [21.18],
       [23.  ],
       [19.97],
       [20.19],
       [34.16],
       [17.83],
       [34.84],
       [26.25],
       [15.64],
       [21.53],
       [14.2 ],
       [16.85],
       [19.93],
       [12.49],
       [18.56],
       [18.93],
       [32.71]])

In [11]:
matriz_imc = np.column_stack([matriz, vetor])

In [12]:
def atribuir_categoria(imc):
    if imc < 16.00:
        return "Baixo peso Grau III"
    elif 16.00 <= imc <= 16.99:
        return "Baixo peso Grau II"
    elif 17.00 <= imc <= 18.49:
        return "Baixo peso Grau I"
    elif 18.50 <= imc <= 24.99:
        return "Peso ideal"
    elif 25.00 <= imc <= 29.99:
        return "Sobrepeso"
    elif 30.00 <= imc <= 34.99:
        return "Obesidade Grau I"
    elif 35.00 <= imc <= 39.99:
        return "Obesidade Grau II"
    else:
        return "Obesidade Grau III"


imc_categoria = np.array(list((map(atribuir_categoria, vetor))))
imc_categoria

array(['Peso ideal', 'Obesidade Grau I', 'Baixo peso Grau III',
       'Peso ideal', 'Peso ideal', 'Peso ideal', 'Peso ideal',
       'Obesidade Grau I', 'Baixo peso Grau I', 'Obesidade Grau I',
       'Sobrepeso', 'Baixo peso Grau III', 'Peso ideal',
       'Baixo peso Grau III', 'Baixo peso Grau II', 'Peso ideal',
       'Baixo peso Grau III', 'Peso ideal', 'Peso ideal',
       'Obesidade Grau I'], dtype='<U19')

In [13]:
matriz_categoria = np.column_stack([matriz_imc.astype(str), imc_categoria])
matriz_categoria

array([['1.788811', '65.648102', '0.0', '20.52', 'Peso ideal'],
       ['1.566784', '76.642768', '0.0', '31.22', 'Obesidade Grau I'],
       ['2.092193', '55.468185', '1.0', '12.67', 'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.18', 'Peso ideal'],
       ['1.735767', '69.289008', '0.0', '23.0', 'Peso ideal'],
       ['1.686975', '56.840051', '0.0', '19.97', 'Peso ideal'],
       ['1.797105', '65.208973', '1.0', '20.19', 'Peso ideal'],
       ['1.187349', '48.164764', '0.0', '34.16', 'Obesidade Grau I'],
       ['1.595891', '45.410648', '1.0', '17.83', 'Baixo peso Grau I'],
       ['1.396282', '67.930113', '0.0', '34.84', 'Obesidade Grau I'],
       ['1.606148', '67.719604', '0.0', '26.25', 'Sobrepeso'],
       ['1.70759', '45.609333', '0.0', '15.64', 'Baixo peso Grau III'],
       ['1.735513', '64.845452', '0.0', '21.53', 'Peso ideal'],
       ['1.672055', '39.705952', '1.0', '14.2', 'Baixo peso Grau III'],
       ['1.723377', '50.05888', '1.0', '16.85', 'Baixo p

In [14]:
colunas = np.array(["Altura", "Peso","Sexo", "IMC",  "Categoria"])
matriz_completa = np.row_stack([colunas, matriz_categoria])
matriz_completa

array([['Altura', 'Peso', 'Sexo', 'IMC', 'Categoria'],
       ['1.788811', '65.648102', '0.0', '20.52', 'Peso ideal'],
       ['1.566784', '76.642768', '0.0', '31.22', 'Obesidade Grau I'],
       ['2.092193', '55.468185', '1.0', '12.67', 'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.18', 'Peso ideal'],
       ['1.735767', '69.289008', '0.0', '23.0', 'Peso ideal'],
       ['1.686975', '56.840051', '0.0', '19.97', 'Peso ideal'],
       ['1.797105', '65.208973', '1.0', '20.19', 'Peso ideal'],
       ['1.187349', '48.164764', '0.0', '34.16', 'Obesidade Grau I'],
       ['1.595891', '45.410648', '1.0', '17.83', 'Baixo peso Grau I'],
       ['1.396282', '67.930113', '0.0', '34.84', 'Obesidade Grau I'],
       ['1.606148', '67.719604', '0.0', '26.25', 'Sobrepeso'],
       ['1.70759', '45.609333', '0.0', '15.64', 'Baixo peso Grau III'],
       ['1.735513', '64.845452', '0.0', '21.53', 'Peso ideal'],
       ['1.672055', '39.705952', '1.0', '14.2', 'Baixo peso Grau III'],
 

In [15]:
np.savetxt("matriz_completa.txt", matriz_completa, fmt='%s', delimiter=",")

### ps: com a configuração 'fmt', os dados foram salvos sem as ', sendo assim no seu formato original.