In [1]:
import numpy as np

### Exercicio 1:
1. Crie um array numpy com valores partindo de 10 até 49
2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
4. Crie uma matriz 4 por 4 de integers preenchida com 5's
5. Crie uma matriz identidade de 3 por 3
6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10


In [94]:
# 1. Crie um array numpy com valores partindo de 10 até 49
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [79]:
# 2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [80]:
# 3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
# 4. Crie uma matriz 4 por 4 de integers preenchida com 5's
np.full((4, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [85]:
# 5. Crie uma matriz identidade de 3 por 3
np.identity((3), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [102]:
# 6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10
np.random.randint(1, 10, 3)

array([7, 6, 4])

### Exercício 2:
1. Dado o array X = np.array(['A','B','C','D','E']) 
Mostre o último elemento
2. Mostre os primeiros 3 elementos
3. Mostre só os elementos do meio
4. Inverta a ordem do array
5. Mostre os elementos nas posições impar.
6. De acordo com a matriz, mostre a primeira linha X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
7. Mostre o primeiro elemento na primeira linha
8. Mostre a linha intermediária
9. Os primeiros 2 elementos das duas primeiras linhas
10. Os últimos 2 elementos das duas últimas linhas

In [119]:
# 1. Dado o array X = np.array(['A','B','C','D','E']) 
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [120]:
# 2. Mostre os primeiros 3 elementos
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [122]:
# 3. Mostre só os elementos do meio
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [123]:
# 4. Inverta a ordem do array
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [125]:
# 5. Mostre os elementos nas posições impar.
X[1::2]

array(['B', 'D'], dtype='<U1')

In [164]:
# 6. De acordo com a matriz, mostre a primeira linha X = np.array([
#    [1,   2,  3,  4],
#    [5,   6,  7,  8],
#    [9,  10, 11, 12],
#    [13, 14, 15, 16]
#])
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])
X[0]

array([1, 2, 3, 4])

In [128]:
# 7. Mostre o primeiro elemento na primeira linha
X[0,0]

1

In [132]:
# 8. Mostre a linha intermediária
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [130]:
# 9. Os primeiros 2 elementos das duas primeiras linhas
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [165]:
# 10. Os últimos 2 elementos das duas últimas linhas
X[2:, 2:]

array([[11, 12],
       [15, 16]])

### Exercicios 3:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor

In [155]:
# 1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
np.sum(X)

43

In [157]:
# 2. Faça a média
np.round(np.average(X), 2)

4.78

In [160]:
#3. Dada a matriz faça a soma das colunas X = np.array([
#    [1,   2,  3,  4],
#    [5,   6,  7,  8],
#    [9,  10, 11, 12],
#    [13, 14, 15, 16]
#])

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [161]:
# 4. Faça a média das linhas
np.average(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [162]:
#5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
#Mostre o elemento de maior valor
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10